version: '3.5'

services:
  nfa_db:
    image: timescale/timescaledb:2.11.0-pg15
    container_name: nfa_db
    command: postgres -c shared_preload_libraries=timescaledb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nfa
    restart: unless-stopped
  nfa_api:
    container_name: nfa_api
    image: quay.io/vktrrdk/traceflow-api:${API_TAG}
    # build:
    #  context: fastapi/
    #  dockerfile: Dockerfile
    ports:
      - "80:8000"
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - nfa_db
    command: bash -c "cd /app/alembic && alembic upgrade head && cd .. && uvicorn main:app --host 0.0.0.0 --port 80"
    restart: unless-stopped
    volumes:
      - ./config/alembic/alembic.ini:/app/alembic/alembic.ini
    networks:
      - nfa
  nfa_ui:
    container_name: nfa_ui
    image: quay.io/vktrrdk/traceflow-ui:${UI_TAG}
    # build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - nfa
    volumes:
      - ./config/vite/vite.config.ts:/var/www/vite.config.ts
networks:
  nfa:
    name: nfa
    driver: bridge